# This file was generated by ansible for localhost
FROM        ansible/ubuntu14.04-ansible:stable

# Volume can be accessed outside of container
#VOLUME      [/var/lib/jenkins]

MAINTAINER  Jason McVetta "https://github.com/jmcvetta"

RUN apt-get update
RUN apt-get dist-upgrade -y

#ENV			DEBIAN_FRONTEND noninteractive
#ENV         JENKINS_HOME /var/lib/jenkins
#ENV         WORKDIR /home/vagrant

ENV	PYTHONUNBUFFERED	true

WORKDIR /tmp/ansible

COPY defaults roles/siliconheavy.liquidfeedback_core/defaults
COPY meta roles/siliconheavy.liquidfeedback_core/meta
COPY handlers roles/siliconheavy.liquidfeedback_core/handlers
COPY tasks roles/siliconheavy.liquidfeedback_core/tasks
COPY vars roles/siliconheavy.liquidfeedback_core/vars

COPY docker-ansible.cfg /etc/ansible/ansible.cfg
COPY docker-hosts /etc/ansible/hosts
COPY docker.yml docker.yml

RUN         ansible-playbook docker.yml -c local 

#TODO improve below port range
#EXPOSE 21:9999
#ENTRYPOINT  ["/etc/init.d/jenkins", "start"]
#CMD ["-g", "deamon off;"]
