# vim:ft=ansible:
---

- name: Download Liquid Feedback Core source code
  get_url:
    url: http://www.public-software-group.org/pub/projects/liquid_feedback/backend/{{ lf_core_version }}/liquid_feedback_core-{{ lf_core_version }}.tar.gz
    dest: /tmp/lf_core.tgz

- name: Unarchive the source code
  unarchive:
    src: /tmp/lf_core.tgz
    dest: "{{ lf_home }}"
    copy: no
    creates: "{{ lf_core_dir }}/core.sql"
